# Generated by Django 5.0.7 on 2025-12-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('1', 'Customer'), ('2', 'Editor'), ('3', 'Vendor')], default='1', max_length=20),
        ),
    ]
